version: 1
module_version: 4.0.0

tests:
  - name: Autoscaler
    project_root: examples/autoscaler

  - name: Bastion
    project_root: examples/bastion
    environment:
      TF_VAR_admin_private_key: ZHVtbXktcHJpdmF0ZS1rZXk=

  - name: Password authentication
    project_root: examples/password-authentication

  - name: System-assigned identity
    project_root: examples/system-assigned-identity

  - name: User-assigned identity
    project_root: examples/user-assigned-identity
